### ISSUE TITLE
BowlerStudio UI Roadmap Discussion

### ISSUE THREAD

**Issue by madhephaestus** [NeuronRobotics/BowlerStudio#1]

**Comment by madhephaestus** [comment]
So i made some updates of the UI layout model in an attempt to make it easier to modify the layout (without recompiling). I made this change so a non-programmer friend could do some work making icons, and having the application load the assets live at runtime. We are now all moved in and ready to start a serious collaboration in UI design/workflow.

**Comment by egolden-bowler** [comment]
Oh good we've got this going again. We sort of lost touch during the move, but I'm ready to get back into the swing of things if you guys are ready again.

**Comment by madhephaestus** [comment]
Yeah, are Saturdays at 3 at Technocopia a possibility for you?

**Comment by egolden-bowler** [comment]
In general yes. But this weekend I've got a commitment. I could make it for 4 or 5 this weekend, and also I'd need to know the new address.

**Comment by madhephaestus** [comment]
44 portland St, Worcester MA, 6th floor.

**Comment by egolden-bowler** [comment]
Okay, see you next Saturday at 3.

**Comment by madhephaestus** [comment]
This issue was moved to CommonWealthRobotics/BowlerStudio#4
