### ISSUE TITLE
Lack of linux .desktop file

### ISSUE THREAD

**Issue by elln2** [NeuronRobotics/BowlerStudio#24]
On linux, it may help to simplify development if a .desktop file were created on the desktop to allow people to start BowlerStudio without needing to remember the command line java argument needed. I would be happy to create a little script to make such a file, as well as a corresponding removal script.

**Comment by madhephaestus** [comment]
The OS files are distributed in their respective installers:

http://neuronrobotics.com/#downloads

and the source for packaging the linux installer can be found here if you want the .desktop separately for some reason:

https://github.com/NeuronRobotics/utils-bowler/tree/master/publish/installer-scripts/linux/build
