### ISSUE TITLE
2d Cad workspace 

### ISSUE THREAD

**Issue by dimitrisTim** [NeuronRobotics/BowlerStudio#26]
Load DXF files and look at them independent of the cad engine, modify them and save out DXFs

**Comment by madhephaestus** [comment]
https://github.com/NeuronRobotics/BowlerStudio/tree/development/src/main/java/com/neuronrobotics/bowlerstudio/twod

**Comment by madhephaestus** [comment]
This issue was moved to CommonWealthRobotics/BowlerStudio#13
