### ISSUE TITLE
No good way to add a file to a gist.

### ISSUE THREAD

**Issue by Octogonapus** [NeuronRobotics/BowlerStudio#32]
The menu option to add a file to a gist should be fixed and enabled.

**Comment by madhephaestus** [comment]
This can be added directly from the gists menu item rather than the generalized add a file menu in the root github menu. The generalized one requires a step where you lookup the gist, which can be skipped with the lower menu

**Comment by madhephaestus** [comment]
This issue was moved to CommonWealthRobotics/BowlerStudio#12
