### ISSUE TITLE
Can not auto-discover a bowler UDP server on a network with staticly defined IP addresses.

### ISSUE THREAD

**Issue by acamilo** [NeuronRobotics/BowlerStudio#35]
### Installed Version

0.15.7.9
### OS type and version number

ubuntu studio 15.10 upgraded from 14.04
kernel 3.13.0-85-lowlatency
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
### Expected behavior

My computer has a statically defined IP address of 192.168.1.5 and the server has 192.168.1.10
There is no router and i am connected with an Ethernet cable.
I can ping the computer running the server.

When I search for servers in the connection dialogue i expect the server field to auto populate with the IP address of the server.
### Actual Behavior

Box is populated with the text "No servers found"
### Steps to reproduce the behavior

Connect to a bowler udp server running on a device with a static IP on a network consisting of two computers with static IPs connected with an Ethernet cable.

**Comment by madhephaestus** [comment]
This issue was moved to CommonWealthRobotics/BowlerStudio#10
