### ISSUE TITLE
JavaFX LoadException upon opening new gist dialog more than once

### ISSUE THREAD

**Issue by Octogonapus** [NeuronRobotics/BowlerStudio#46]
### Installed Version 
0.17.0
### OS type and version number
Window 7 SP1
### Expected behavior
The dialog should open like normal (not much to say, this is pretty standard behaviour).
### Actual Behavior
LoadException is thrown, "Root value already specified." Dialog does not show after the first opening.
### Steps to reproduce the behavior
Open the create new gist dialog more than once.

**Comment by madhephaestus** [comment]
The syntax to auto-close woulf be to make the first line of a commit "close #46")
