### ISSUE TITLE
No way to change asset repository

### ISSUE THREAD

**Issue by Octogonapus** [NeuronRobotics/BowlerStudio#48]
Now that the functionality is in to use different asset repositories, there should be a way to change which one a user is using from the default to their own fork. Apart from the obvious, this would also help finalize a solution to issue #32.

**Comment by madhephaestus** [comment]
This is blocked by #49

**Comment by madhephaestus** [comment]
This issue was moved to CommonWealthRobotics/BowlerStudio#9
