### ISSUE TITLE
BS v0.4.3 in win7x64 crashes after a minute or two of holding down one of the movement keys.

### ISSUE THREAD

**Issue by acamilo** [NeuronRobotics/BowlerStudio#52]
fire it up in windows, connect DyIO, 6 leg walker.
hold down any of the movement keys.
it goes and then after a while it stops and UI controls are unresponsive requiring a reset of BS

**Comment by madhephaestus** [comment]
i suspect this is a DyIo issue percolating up, it shouldnt crash though..
