### ISSUE TITLE
Windows version installer signing

### ISSUE THREAD

**Issue by scj643** [NeuronRobotics/BowlerStudio#56]
If possible the windows installer should be code signed so Windows doesn't mark it as suspicious.

**Comment by madhephaestus** [comment]
Yeah, the installer packing scripts for WIndows is found here: https://github.com/NeuronRobotics/utils-bowler/tree/master/publish/installer-scripts/windows

I use InnoIDE to build the installer. I tried to get a signed cert a few month back, but ran int a lot of problems getting my signature set up (for free, this is an open source project worked on by only me, so i have no funds for this sort of thing). It has been placed on low priority and will stay there until getting the signatures registered becomes easier, or windows begins flatly refuse to run unsigned code.  

I you want to voulinteer to help set up a TravisCI based auto builder, one that signes the windows installers along with building the Mac and debian binaries (debian IS signed and deployed through a PPA), i would much appreciate the help ;)

**Comment by madhephaestus** [comment]
This issue was moved to CommonWealthRobotics/BowlerStudio#7
