### ISSUE TITLE
Can't read file names with spaces

### ISSUE THREAD

**Issue by myufus** [NeuronRobotics/BowlerStudio#58]
### Installed Version

0.19.4
### OS type and version number

Windows 10
### Expected behavior

Runs Arduino script for communication with Teensy
### Actual Behavior

Displays error: Must specify exactly one sketch file
### Steps to reproduce the behavior

Attempt running Arduino sketches through Bowler from user account or folder with whitespace

**Comment by madhephaestus** [comment]
This issue was moved to CommonWealthRobotics/BowlerStudio#5
