### ISSUE TITLE
Add a login so that if you login to BowlerStudio it logs you into the browser

### ISSUE THREAD

**Issue by madhephaestus** [NeuronRobotics/BowlerStudio#9]
The application logs into github, so it would be nice if this also logged in the Browser version of github.

**Comment by dimitrisTim** [comment]
You mean it should open a new tab inside the BowlerStudio, that is the Github Url of the user?

**Comment by madhephaestus** [comment]
This issue takes a few steps
* FIrst a function needs to be added to the kernel repo to resolve https://github.com/NeuronRobotics/bowler-script-kernel/issues/1

* Next you need to use that function in the ScriptingGistTab.java to generate login authentication cookie for GitHub

* Finally you need to load this cookie on the event of login, and remove it on the event of logout or close of applicaiton

**Comment by madhephaestus** [comment]
This issue was moved to CommonWealthRobotics/BowlerStudio#16
